
post http://localhost:3003/seats
content-Type: application/json

{
    "name": "A2"
}

###

get http://localhost:3003/seats
content-Type: application/json
###

post http://localhost:3003/movies
content-Type: application/json

{
    "movieId": "12477"
}
###


get http://localhost:3003/api/seats/66445855e198f7ce93ee4317
content-Type: application/json
###

get http://localhost:3003/movies
content-Type: application/json