
post http://localhost:3003/seats
content-Type: application/json

{
    "name": "A2"
}

###

get http://localhost:3003/seats
content-Type: application/json

###
get http://localhost:3003/seats/66445855e198f7ce93ee4317
content-Type: application/json
###










post http://localhost:3003/movies
content-Type: application/json

{
    "movieId": "97075"
}
###


get http://localhost:3003/movies
content-Type: application/json

###



post http://localhost:3003/schedule
content-Type: application/json

{
    "movie": "665033be8835b6058c9cdbd9",
    "time": "1pm",
    "date": "5"
}
###

get http://localhost:3003/schedule/5
content-Type: application/json

###